spring:
  #  数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hhnail
    username: root
#    雷神笔记本
    password: 123456
#    默认密码
#    password: root
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
mybatis-plus:
  configuration:
    #    mybatis日志（查看数据流、最终的sql等）
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    驼峰命名自动映射   eg：userName —> user_name
    map-underscore-to-camel-case: true
#    mapper-location: mapper/*.xml
#服务
server:
#  端口号
  port: 18080

